import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.95.0/+esm';
const supabase=createClient('https://ulzlkewtarzajseepbvj.supabase.co','sb_publishable_hkRBpDIfH3_GFDUDJtygoQ_ItfkONsi');
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
let rows=[],generation=0;
function message(id,s,kind=''){ $(id).textContent=s;$(id).className=kind; }
async function api(body){const {data,error}=await supabase.functions.invoke('candidate-portal',{body});if(error){let msg=error.message;try{msg=(await error.context.json()).error||msg;}catch{}throw new Error(msg);}return data;}
const list=items=>`<ul>${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`;
function render(){const shown=rows.filter(r=>$('filter').value==='all'||r.status===$('filter').value);$('count').textContent=`${shown.length} of ${rows.length} saved roles`;
 $('roles').innerHTML=shown.length?shown.map(r=>{const e=r.evaluation,u=safeUrl(r.source_url);return `<article class="role" data-id="${esc(r.id)}"><span class="badge">${e?`${esc(e.score)}/100 · ${esc(e.fitBand)}`:'Suggested for review · Not scored'}</span><h3>${esc(r.title)}</h3><p class="muted">${esc(r.company)} · ${esc(r.location_text||'Location unknown')}</p>${e?`<details><summary>Why this may fit</summary>${list(e.reasons||[])}</details><details open><summary>What to check</summary>${list(e.gaps||['Confirm all essential requirements.'])}</details>`:'<p>This is a curated summary. Import the full posting before evaluating your match.</p>'}<p>${esc(r.review_notes)}</p><details><summary>Saved job details</summary><p class="description">${esc(r.description)}</p><p class="muted">Saved ${esc(new Date(r.updated_at).toLocaleDateString())}; confirm the role is still open.</p></details>${u?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">Open original job ↗</a><br><button data-import="true">${e?'Refresh job':'Import and evaluate'}</button>`:''}<div class="feedback"><p>What do you think?</p>${[['interested','Interested'],['pass','Pass'],['applied','Already applied'],['new','Review later']].map(([s,l])=>`<button data-status="${s}" aria-pressed="${r.status===s}">${l}</button>`).join('')}<label for="note-${esc(r.id)}">Optional note</label><textarea id="note-${esc(r.id)}" maxlength="1000" rows="2">${esc(r.feedback_note)}</textarea><button data-note="true">Save note</button><p class="result" role="status"></p></div></article>`;}).join(''):'<p>No roles in this view. Check another job below.</p>';
}
async function reload(){const g=generation,data=await api({action:'list'});if(g!==generation)return;rows=data.roles;$('welcome').textContent=`Welcome, ${data.profile.name}`;render();}
async function sessionChanged(session){const g=++generation;rows=[];$('roles').replaceChildren();$('workspace').hidden=true;$('authPanel').hidden=!!session;$('sessionBar').hidden=!session;$('sessionEmail').textContent=session?.user?.email||'';if(!session){message('message','');return;}message('message','Loading your opportunities…');try{await reload();if(g===generation){$('workspace').hidden=false;message('message','');}}catch(e){if(g===generation)message('message',e.message,'error');}}
$('login').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const {error}=await supabase.auth.signInWithOtp({email:$('email').value.trim(),options:{emailRedirectTo:new URL('placement.html',location.href).href}});message('authStatus',error?error.message:'Check your email for the secure sign-in link.',error?'error':'success');}finally{button.disabled=false;}});
$('signOut').addEventListener('click',async()=>{const {error}=await supabase.auth.signOut();if(error)message('message',error.message,'error');});
$('filter').addEventListener('change',render);
$('roles').addEventListener('click',async e=>{const button=e.target.closest('button'),card=button?.closest('[data-id]');if(!card)return;const row=rows.find(r=>r.id===card.dataset.id);if(!row)return;if(button.dataset.import){$('jobForm').reset();$('jobUrl').value=row.source_url;$('jobForm').dataset.refresh='true';$('importPanel').scrollIntoView({behavior:'smooth'});message('importStatus','Select Evaluate and save to read the full posting.');return;}
 const g=generation,output=card.querySelector('.result');card.querySelectorAll('button').forEach(b=>b.disabled=true);output.textContent='Saving…';try{const result=await api({action:'feedback',id:row.id,status:button.dataset.status||row.status,note:card.querySelector('textarea').value});if(g!==generation)return;Object.assign(row,result);render();message('message','Feedback saved.','success');}catch(e){if(g===generation){output.textContent=e.message;card.querySelectorAll('button').forEach(b=>b.disabled=false);}}});
$('jobForm').addEventListener('submit',async e=>{e.preventDefault();const g=generation;$('evaluate').disabled=true;message('importStatus','Reading the job and checking your experience…');try{const result=await api({action:'import',...Object.fromEntries(new FormData(e.target)),refresh:e.target.dataset.refresh==='true'});if(g!==generation)return;await reload();$('filter').value='all';render();message('importStatus',result.reused?'Already saved above. Choose Refresh job to reread it.':'Evaluated and saved. Review the job details and gaps above.','success');e.target.reset();delete e.target.dataset.refresh;}catch(e){if(g===generation){message('importStatus',e.message,'error');$('pasteFields').open=true;}}finally{$('evaluate').disabled=false;}});
supabase.auth.onAuthStateChange((event,session)=>{if(event!=='TOKEN_REFRESHED')setTimeout(()=>sessionChanged(session),0);});
const {data:{session}}=await supabase.auth.getSession();await sessionChanged(session);
