import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler,completeDescription} from '../supabase/functions/candidate-portal/handler.ts';
import {includesPhrase,inferSeniority,locationScore} from '../supabase/functions/candidate-portal/scoring.ts';
import {extractJobPostingHtml,importJobFromUrl} from '../supabase/functions/candidate-portal/job-import.ts';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const full='Responsibilities include owning product strategy, coordinating customer research and working with engineering to deliver useful customer outcomes. Requirements include demonstrated product management experience, strong communication skills and the ability to lead cross functional projects. You will define priorities, review feedback, measure adoption, improve workflows, communicate risks and partner with customers throughout delivery. Candidates should provide examples of successful launches and explain how their experience relates to the requirements of this opportunity. We value evidence, clear thinking and collaborative execution.';
function setup({email='a@example.test',confirmed=true,opted=true,enabled=true}={}){
 const tables={candidate_portal_access:[{email:'a@example.test',candidate_id:A,active:enabled},{email:'b@example.test',candidate_id:B,active:true}],network_members:[{id:A,first_name:'A',last_name:'Test',matching_opt_in:opted,public_skills:[]},{id:B,first_name:'B',last_name:'Test',matching_opt_in:true}],candidate_saved_roles:[{id:A,candidate_id:A,source_url:'https://jobs.lever.co/a/1',status:'interested',feedback_note:'keep',job_id:null},{id:B,candidate_id:B,source_url:'https://jobs.lever.co/b/1',status:'new',feedback_note:'private',job_id:null}],candidate_features:[{candidate_id:A,skills:[],domains:[],evidence:{}}],candidate_role_preferences:[],role_taxonomy:[]};
 const db={rpc:async()=>({data:true}),from(name){let filters=[],op='',value,one=false;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},maybeSingle(){one=true;return q},single(){one=true;return q},update(v){op='update';value=v;return q},upsert(v){op='upsert';value=v;return q},then(resolve){let rows=tables[name].filter(r=>filters.every(([k,v])=>r[k]===v));if(op==='update')rows.forEach(r=>Object.assign(r,value));if(op==='upsert'){let r=tables[name].find(r=>r.candidate_id===value.candidate_id&&r.source_url===value.source_url);if(r)Object.assign(r,value);else{r={id:crypto.randomUUID(),status:'new',feedback_note:'',...value};tables[name].push(r);}rows=[r];}return Promise.resolve({data:one?rows[0]||null:rows}).then(resolve);}};return q;}};
 const auth={getUser:async()=>({data:{user:{email,email_confirmed_at:confirmed?'2026-09-01':null}}})};
 return {tables,handler:createHandler({auth,db,importJob:async url=>({canonicalUrl:url,title:'Product Manager',description:full,location:'',remoteType:''})})};
}
const request=(body,token='test')=>new Request('https://example.test',{method:'POST',headers:token?{authorization:'Bearer '+token}:{},body:JSON.stringify(body)});
test('anonymous request rejected',async()=>assert.equal((await setup().handler(request({action:'list'},''))).status,401));
test('unverified email rejected',async()=>assert.equal((await setup({confirmed:false}).handler(request({action:'list'}))).status,401));
test('unlisted account rejected',async()=>assert.equal((await setup({email:'other@example.test'}).handler(request({action:'list'}))).status,403));
test('revoked access and opted-out profile rejected',async()=>{for(const options of [{enabled:false},{opted:false}])assert.equal((await setup(options).handler(request({action:'list'}))).status,403);});
test('caller cannot choose another profile',async()=>{const r=await setup().handler(request({action:'list',candidate_id:B}));const data=await r.json();assert.equal(data.roles.length,1);assert.equal(data.roles[0].id,A);});
test('cross-candidate feedback blocked',async()=>{const {handler,tables}=setup();assert.equal((await handler(request({action:'feedback',id:B,status:'pass',note:'attack'}))).status,404);assert.equal(tables.candidate_saved_roles[1].feedback_note,'private');});
test('own feedback saved, score and owner injection ignored',async()=>{const {handler,tables}=setup();assert.equal((await handler(request({action:'feedback',id:A,status:'applied',note:'done',candidate_id:B,evaluation:{score:100}}))).status,200);assert.equal(tables.candidate_saved_roles[0].candidate_id,A);assert.equal(tables.candidate_saved_roles[0].evaluation,undefined);assert.equal(tables.candidate_saved_roles[0].status,'applied');});
test('repeat URL reuses saved role',async()=>{const {handler,tables}=setup();assert.equal((await (await handler(request({action:'import',jobUrl:'https://jobs.lever.co/a/1'}))).json()).reused,true);assert.equal(tables.candidate_saved_roles.length,2);});
test('refresh preserves status and note and evaluates only own profile',async()=>{const {handler,tables}=setup();const r=await handler(request({action:'import',jobUrl:'https://jobs.lever.co/a/1',refresh:true,candidate_id:B}));assert.equal(r.status,200);const row=tables.candidate_saved_roles[0];assert.equal(row.status,'interested');assert.equal(row.feedback_note,'keep');assert.ok(row.evaluation);assert.equal(row.evaluation.candidate,undefined);assert.equal(tables.candidate_saved_roles[1].evaluation,undefined);});
test('reject summaries and metadata-only jobs',()=>{assert.equal(completeDescription('short summary'),false);assert.throws(()=>extractJobPostingHtml('<title>Director</title><meta name="description" content="'+full+'">','https://jobs.lever.co/a/1'));});
test('full structured job accepted; expired posting rejected',()=>{const html=job=>`<script type="application/ld+json">${JSON.stringify(job)}</script>`;assert.equal(extractJobPostingHtml(html({'@type':'JobPosting',title:'Product Manager',description:full}),'https://jobs.lever.co/a/1').title,'Product Manager');assert.throws(()=>extractJobPostingHtml(html({'@type':'JobPosting',title:'Product Manager',description:full,validThrough:'2020-01-01'}),'https://jobs.lever.co/a/1'));});
test('import host allowlist prevents arbitrary network access',async()=>assert.rejects(()=>importJobFromUrl('https://example.test/job'),/not supported/));
test('Go does not match goals or go-to-market; senior manager title retains seniority',()=>{assert.equal(includesPhrase('go to market goals','Go'),false);assert.equal(includesPhrase('golang programming','Go'),true);assert.equal(inferSeniority('Senior Product Manager','partner with the director'),'senior');});
test('remote does not earn full location credit',()=>{const result=locationScore('New York','Toronto','Remote');assert.equal(result.aligned,false);assert.equal(result.score,5);});
